#include "yql_syntax.h"

#include <ydb/library/yql/parser/proto_ast/gen/v1_antlr4/SQLv1Antlr4Lexer.h>

namespace NYdb {
    namespace NConsoleClient {

        bool IsYQLKeyword(size_t token_type) {
            switch (token_type) {
                case TOKEN(ABORT):
                case TOKEN(ACTION):
                case TOKEN(ADD):
                case TOKEN(AFTER):
                case TOKEN(ALL):
                case TOKEN(ALTER):
                case TOKEN(ANALYZE):
                case TOKEN(AND):
                case TOKEN(ANSI):
                case TOKEN(ANY):
                case TOKEN(ARRAY):
                case TOKEN(AS):
                case TOKEN(ASC):
                case TOKEN(ASSUME):
                case TOKEN(ASYMMETRIC):
                case TOKEN(ASYNC):
                case TOKEN(ATTACH):
                case TOKEN(ATTRIBUTES):
                case TOKEN(AUTOINCREMENT):
                case TOKEN(AUTOMAP):
                case TOKEN(BEFORE):
                case TOKEN(BEGIN):
                case TOKEN(BERNOULLI):
                case TOKEN(BETWEEN):
                case TOKEN(BITCAST):
                case TOKEN(BY):
                case TOKEN(CALLABLE):
                case TOKEN(CASCADE):
                case TOKEN(CASE):
                case TOKEN(CAST):
                case TOKEN(CHANGEFEED):
                case TOKEN(CHECK):
                case TOKEN(COLLATE):
                case TOKEN(COLUMN):
                case TOKEN(COLUMNS):
                case TOKEN(COMMIT):
                case TOKEN(COMPACT):
                case TOKEN(CONDITIONAL):
                case TOKEN(CONFLICT):
                case TOKEN(CONNECT):
                case TOKEN(CONSTRAINT):
                case TOKEN(CONSUMER):
                case TOKEN(COVER):
                case TOKEN(CREATE):
                case TOKEN(CROSS):
                case TOKEN(CUBE):
                case TOKEN(CURRENT):
                case TOKEN(CURRENT_DATE):
                case TOKEN(CURRENT_TIME):
                case TOKEN(CURRENT_TIMESTAMP):
                case TOKEN(DATA):
                case TOKEN(DATABASE):
                case TOKEN(DECIMAL):
                case TOKEN(DECLARE):
                case TOKEN(DEFAULT):
                case TOKEN(DEFERRABLE):
                case TOKEN(DEFERRED):
                case TOKEN(DEFINE):
                case TOKEN(DELETE):
                case TOKEN(DESC):
                case TOKEN(DESCRIBE):
                case TOKEN(DETACH):
                case TOKEN(DICT):
                case TOKEN(DIRECTORY):
                case TOKEN(DISABLE):
                case TOKEN(DISCARD):
                case TOKEN(DISTINCT):
                case TOKEN(DO):
                case TOKEN(DROP):
                case TOKEN(EACH):
                case TOKEN(ELSE):
                case TOKEN(EMPTY):
                case TOKEN(EMPTY_ACTION):
                case TOKEN(ENCRYPTED):
                case TOKEN(END):
                case TOKEN(ENUM):
                case TOKEN(ERASE):
                case TOKEN(ERROR):
                case TOKEN(ESCAPE):
                case TOKEN(EVALUATE):
                case TOKEN(EXCEPT):
                case TOKEN(EXCLUDE):
                case TOKEN(EXCLUSION):
                case TOKEN(EXCLUSIVE):
                case TOKEN(EXISTS):
                case TOKEN(EXPLAIN):
                case TOKEN(EXPORT):
                case TOKEN(EXTERNAL):
                case TOKEN(FAIL):
                case TOKEN(FALSE):
                case TOKEN(FAMILY):
                case TOKEN(FILTER):
                case TOKEN(FIRST):
                case TOKEN(FLATTEN):
                case TOKEN(FLOW):
                case TOKEN(FOLLOWING):
                case TOKEN(FOR):
                case TOKEN(FOREIGN):
                case TOKEN(FROM):
                case TOKEN(FULL):
                case TOKEN(FUNCTION):
                case TOKEN(GLOB):
                case TOKEN(GLOBAL):
                case TOKEN(GRANT):
                case TOKEN(GROUP):
                case TOKEN(GROUPING):
                case TOKEN(GROUPS):
                case TOKEN(HASH):
                case TOKEN(HAVING):
                case TOKEN(HOP):
                case TOKEN(IF):
                case TOKEN(IGNORE):
                case TOKEN(ILIKE):
                case TOKEN(IMMEDIATE):
                case TOKEN(IMPORT):
                case TOKEN(IN):
                case TOKEN(INDEX):
                case TOKEN(INDEXED):
                case TOKEN(INHERITS):
                case TOKEN(INITIAL):
                case TOKEN(INITIALLY):
                case TOKEN(INNER):
                case TOKEN(INSERT):
                case TOKEN(INSTEAD):
                case TOKEN(INTERSECT):
                case TOKEN(INTO):
                case TOKEN(IS):
                case TOKEN(ISNULL):
                case TOKEN(JOIN):
                case TOKEN(JSON_EXISTS):
                case TOKEN(JSON_QUERY):
                case TOKEN(JSON_VALUE):
                case TOKEN(KEY):
                case TOKEN(LAST):
                case TOKEN(LEFT):
                case TOKEN(LEGACY):
                case TOKEN(LIKE):
                case TOKEN(LIMIT):
                case TOKEN(LIST):
                case TOKEN(LOCAL):
                case TOKEN(MANAGE):
                case TOKEN(MATCH):
                case TOKEN(MATCHES):
                case TOKEN(MATCH_RECOGNIZE):
                case TOKEN(MEASURES):
                case TOKEN(MICROSECONDS):
                case TOKEN(MILLISECONDS):
                case TOKEN(MODIFY):
                case TOKEN(NANOSECONDS):
                case TOKEN(NATURAL):
                case TOKEN(NEXT):
                case TOKEN(NO):
                case TOKEN(NOT):
                case TOKEN(NOTNULL):
                case TOKEN(NULL):
                case TOKEN(NULLS):
                case TOKEN(OBJECT):
                case TOKEN(OF):
                case TOKEN(OFFSET):
                case TOKEN(OMIT):
                case TOKEN(ON):
                case TOKEN(ONE):
                case TOKEN(ONLY):
                case TOKEN(OPTION):
                case TOKEN(OPTIONAL):
                case TOKEN(OR):
                case TOKEN(ORDER):
                case TOKEN(OTHERS):
                case TOKEN(OUTER):
                case TOKEN(OVER):
                case TOKEN(PARALLEL):
                case TOKEN(PARTITION):
                case TOKEN(PASSING):
                case TOKEN(PASSWORD):
                case TOKEN(PAST):
                case TOKEN(PATTERN):
                case TOKEN(PER):
                case TOKEN(PERMUTE):
                case TOKEN(PLAN):
                case TOKEN(PRAGMA):
                case TOKEN(PRECEDING):
                case TOKEN(PRESORT):
                case TOKEN(PRIMARY):
                case TOKEN(PRIVILEGES):
                case TOKEN(PROCESS):
                case TOKEN(QUEUE):
                case TOKEN(RAISE):
                case TOKEN(RANGE):
                case TOKEN(REDUCE):
                case TOKEN(REFERENCES):
                case TOKEN(REGEXP):
                case TOKEN(REINDEX):
                case TOKEN(RELEASE):
                case TOKEN(REMOVE):
                case TOKEN(RENAME):
                case TOKEN(REPEATABLE):
                case TOKEN(REPLACE):
                case TOKEN(REPLICATION):
                case TOKEN(RESET):
                case TOKEN(RESOURCE):
                case TOKEN(RESPECT):
                case TOKEN(RESTRICT):
                case TOKEN(RESULT):
                case TOKEN(RETURN):
                case TOKEN(RETURNING):
                case TOKEN(REVERT):
                case TOKEN(REVOKE):
                case TOKEN(RIGHT):
                case TOKEN(RLIKE):
                case TOKEN(ROLLBACK):
                case TOKEN(ROLLUP):
                case TOKEN(ROW):
                case TOKEN(ROWS):
                case TOKEN(SAMPLE):
                case TOKEN(SAVEPOINT):
                case TOKEN(SCHEMA):
                case TOKEN(SECONDS):
                case TOKEN(SEEK):
                case TOKEN(SELECT):
                case TOKEN(SEMI):
                case TOKEN(SET):
                case TOKEN(SETS):
                case TOKEN(SHOW):
                case TOKEN(SOURCE):
                case TOKEN(STREAM):
                case TOKEN(STRUCT):
                case TOKEN(SUBQUERY):
                case TOKEN(SUBSET):
                case TOKEN(SYMBOLS):
                case TOKEN(SYMMETRIC):
                case TOKEN(SYNC):
                case TOKEN(SYSTEM):
                case TOKEN(TABLE):
                case TOKEN(TABLES):
                case TOKEN(TABLESAMPLE):
                case TOKEN(TABLESTORE):
                case TOKEN(TAGGED):
                case TOKEN(TEMP):
                case TOKEN(TEMPORARY):
                case TOKEN(THEN):
                case TOKEN(TIES):
                case TOKEN(TO):
                case TOKEN(TOPIC):
                case TOKEN(TRANSACTION):
                case TOKEN(TRIGGER):
                case TOKEN(TRUE):
                case TOKEN(TUPLE):
                case TOKEN(TYPE):
                case TOKEN(UNBOUNDED):
                case TOKEN(UNCONDITIONAL):
                case TOKEN(UNION):
                case TOKEN(UNIQUE):
                case TOKEN(UNKNOWN):
                case TOKEN(UNMATCHED):
                case TOKEN(UPDATE):
                case TOKEN(UPSERT):
                case TOKEN(USE):
                case TOKEN(USER):
                case TOKEN(USING):
                case TOKEN(VACUUM):
                case TOKEN(VALUES):
                case TOKEN(VARIANT):
                case TOKEN(VIEW):
                case TOKEN(VIRTUAL):
                case TOKEN(WHEN):
                case TOKEN(WHERE):
                case TOKEN(WINDOW):
                case TOKEN(WITH):
                case TOKEN(WITHOUT):
                case TOKEN(WRAPPER):
                case TOKEN(XOR):
                    return true;
                default:
                    return false;
            }
        }

    }
}
